name: 'Run SSH4Me'
on:
 workflow_dispatch:
jobs:
 build-and-run:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       - name: Run SSH4Me Action
         uses: Jisan09/SSH4Me@main
         env:
          AUTH_TOKEN: 2jIRmpNMY0iQ0CJPc0RJ879Fx3x_44mr42xKFf5vMQhw7LA3N
          PASSWORD: 0988
